Ambience.AddSong(SONG_IDLE, "Black Mesa Inbound", "music/hl1_song3.mp3")
Ambience.AddSong(SONG_IDLE, "Escape Array", "music/hl1_song20.mp3")
Ambience.AddSong(SONG_IDLE, "Dirac Shore", "music/hl1_song21.mp3")
Ambience.AddSong(SONG_IDLE, "Entanglement", "music/hl2_song0.mp3")
Ambience.AddSong(SONG_IDLE, "Particle Ghost", "music/hl2_song1.mp3")
Ambience.AddSong(SONG_IDLE, "Lab Practicum", "music/hl2_song2.mp3")
Ambience.AddSong(SONG_IDLE, "Highway 17", "music/hl2_song8.mp3")
Ambience.AddSong(SONG_IDLE, "A Red Letter Day", "music/hl2_song10.mp3")
Ambience.AddSong(SONG_IDLE, "Sandtraps", "music/hl2_song11.mp3")
Ambience.AddSong(SONG_IDLE, "Suppression Field", "music/hl2_song13.mp3")
Ambience.AddSong(SONG_IDLE, "Broken Symmetry", "music/hl2_song17.mp3")
Ambience.AddSong(SONG_IDLE, "Nova Prospekt", "music/hl2_song19.mp3")
Ambience.AddSong(SONG_IDLE, "Train Station 1", "music/hl2_song26_trainstation1.mp3")
Ambience.AddSong(SONG_IDLE, "Train Station 2", "music/hl2_song27_trainstation2.mp3")
Ambience.AddSong(SONG_IDLE, "Calabi-Yau Model", "music/hl2_song30.mp3")
Ambience.AddSong(SONG_IDLE, "Inhuman Frequency", "music/vlvx_song26.mp3")
Ambience.AddSong(SONG_IDLE, "Eine Kleiner Elevatormuzik", "music/vlvx_song1.mp3")
Ambience.AddSong(SONG_IDLE, "Combine Advisory", "music/vlvx_song2.mp3")
Ambience.AddSong(SONG_IDLE, "Dark Interval", "music/vlvx_song3.mp3")
Ambience.AddSong(SONG_IDLE, "Darkness At Noon", "music/vlvx_song8.mp3")
Ambience.AddSong(SONG_IDLE, "Nectarium", "music/vlvx_song15.mp3")
Ambience.AddSong(SONG_IDLE, "Infraradiant", "music/vlvx_song19a.mp3")
Ambience.AddSong(SONG_IDLE, "Extinction Event Horizon", "music/vlvx_song20.mp3")
Ambience.AddSong(SONG_IDLE, "Shu'ulathoi", "music/vlvx_song23ambient.mp3")

Ambience.AddSong(SONG_ALERT, "Echoes of a Resonance Cascade", "music/hl1_song5.mp3")
Ambience.AddSong(SONG_ALERT, "Zero Point Energy Field", "music/hl1_song6.mp3")
Ambience.AddSong(SONG_ALERT, "Neutrino Trap", "music/hl1_song9.mp3")
Ambience.AddSong(SONG_ALERT, "Hazardous Environments", "music/hl1_song11.mp3")
Ambience.AddSong(SONG_ALERT, "Triple Entanglement", "music/hl1_song14.mp3")
Ambience.AddSong(SONG_ALERT, "Tau-9", "music/hl1_song17.mp3")
Ambience.AddSong(SONG_ALERT, "Negative Pressure", "music/hl1_song19.mp3")
Ambience.AddSong(SONG_ALERT, "Singularity", "music/hl1_song24.mp3")
Ambience.AddSong(SONG_ALERT, "Xen Relay", "music/hl1_song26.mp3")
Ambience.AddSong(SONG_ALERT, "Ravenholm Reprise", "music/hl2_song7.mp3")
Ambience.AddSong(SONG_ALERT, "Triage At Dawn", "music/hl2_song23_suitsong3.mp3")
Ambience.AddSong(SONG_ALERT, "Miscount Detected", "music/hl2_song25_teleporter.mp3")
Ambience.AddSong(SONG_ALERT, "Our Resurrected Teleport", "music/hl2_song26.mp3")
Ambience.AddSong(SONG_ALERT, "Hunter Down", "music/hl2_song28.mp3")
Ambience.AddSong(SONG_ALERT, "Brane Scan", "music/hl2_song31.mp3")
Ambience.AddSong(SONG_ALERT, "Slow Light", "music/hl2_song32.mp3")
Ambience.AddSong(SONG_ALERT, "Probably Not a Problem", "music/hl2_song33.mp3")
Ambience.AddSong(SONG_ALERT, "Requiem For Ravenholm", "music/ravenholm_1.mp3")
Ambience.AddSong(SONG_ALERT, "No One Rides For Free", "music/vlvx_song0.mp3")
Ambience.AddSong(SONG_ALERT, "Guard Down", "music/vlvx_song4.mp3")
Ambience.AddSong(SONG_ALERT, "Crawl Yard", "music/vlvx_song9.mp3")
Ambience.AddSong(SONG_ALERT, "Decay Mode", "music/vlvx_song19b.mp3")
Ambience.AddSong(SONG_ALERT, "Abandoned In Place", "music/vlvx_song25.mp3")
Ambience.AddSong(SONG_ALERT, "Eon Trap", "music/vlvx_song28.mp3")

Ambience.AddSong(SONG_ACTION, "Lambda Core", "music/hl1_song10.mp3")
Ambience.AddSong(SONG_ACTION, "Something Secret Steers Us", "music/hl1_song15.mp3")
Ambience.AddSong(SONG_ACTION, "Tracking Device", "music/hl1_song25_remix3.mp3")
Ambience.AddSong(SONG_ACTION, "Dark Energy", "music/hl2_song3.mp3")
Ambience.AddSong(SONG_ACTION, "The Innsbruck Experiment", "music/hl2_song4.mp3")
Ambience.AddSong(SONG_ACTION, "Pulse Phase", "music/hl2_song6.mp3")
Ambience.AddSong(SONG_ACTION, "Hard Fought", "music/hl2_song12_long.mp3")
Ambience.AddSong(SONG_ACTION, "You're Not Supposed to Be Here", "music/hl2_song14.mp3")
Ambience.AddSong(SONG_ACTION, "Kaon", "music/hl2_song15.mp3")
Ambience.AddSong(SONG_ACTION, "LG Orbifold", "music/hl2_song16.mp3")
Ambience.AddSong(SONG_ACTION, "CP Violation", "music/hl2_song20_submix0.mp3")
Ambience.AddSong(SONG_ACTION, "CP Violation (remix)", "music/hl2_song20_submix4.mp3")
Ambience.AddSong(SONG_ACTION, "Apprehension and Evasion", "music/hl2_song29.mp3")
Ambience.AddSong(SONG_ACTION, "Disrupted Original", "music/vlvx_song11.mp3")
Ambience.AddSong(SONG_ACTION, "Self Destruction", "music/vlvx_song12.mp3")
Ambience.AddSong(SONG_ACTION, "What Kind Of Hospital Is This?", "music/vlvx_song18.mp3")
Ambience.AddSong(SONG_ACTION, "Penultimatum", "music/vlvx_song21.mp3")
Ambience.AddSong(SONG_ACTION, "Vortal Combat", "music/vlvx_song22.mp3")
Ambience.AddSong(SONG_ACTION, "Sector Sweep", "music/vlvx_song23.mp3")
Ambience.AddSong(SONG_ACTION, "Last Legs", "music/vlvx_song24.mp3")
Ambience.AddSong(SONG_ACTION, "Hunting Party", "music/vlvx_song27.mp3")

Ambience.AddSong(SONG_STINGER, "Industrial Suspense 1", "music/stingers/industrial_suspense1.wav")
Ambience.AddSong(SONG_STINGER, "Industrial Suspense 2", "music/stingers/industrial_suspense2.wav")
Ambience.AddSong(SONG_STINGER, "Apprehensive", "music/stingers/hl1_stinger_song7.mp3")
Ambience.AddSong(SONG_STINGER, "Bass String", "music/stingers/hl1_stinger_song8.mp3")
Ambience.AddSong(SONG_STINGER, "Scared Confusion", "music/stingers/hl1_stinger_song16.mp3")
Ambience.AddSong(SONG_STINGER, "Dark Piano", "music/stingers/hl1_stinger_song27.mp3")
Ambience.AddSong(SONG_STINGER, "Sharp Piano", "music/stingers/hl1_stinger_song28.mp3")

-- Ambience.AddSong(SONG_DISPATCH, "Anti-Citizen Reported", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Charged With Anti-Civil Activity Level 1", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Evidence Of Anti-Civil Activity", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Charged With Capital Malcompliance", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Charged With Socio-Endangerment Level 5; Cease Evasion", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Citizenship Revoked; Status: Malignant", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Unidentified POI Confirm Civil Status", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Evasion Behavior Consistent With Malcompliant", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Inaction Is Conspiracy", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Local Unrest Structure Detected", "npc/overwatch/cityvoice/f_localunrest_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Status Evasion In Progress", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Autonomous Judgement Waiver", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Judgement Waiver", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Charged With Permissive Inactive Coercion", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Charged With Socio-Endangerment Level 1", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Priority Identification Check In Progress", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Assume Your Inspection Positions", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Miscount Detected", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Potential Civil Infection", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Failure To Cooperate Will Result In", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Unrest Procedure Is Now In Effect", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Overwatch Acknowledges Critical Exogen Breach", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Mission Failure Will Result In", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav")
-- Ambience.AddSong(SONG_DISPATCH, "Non-Standard Exogen Activity Detected", "npc/overwatch/cityvoice/fprison_nonstandardexogen.wav")
